### Statistics Practices

In [ ]:
### https://github.com/mwaskom/seaborn-data    
## seaborn data seti

In [1]:
import seaborn as sns

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [3]:
df = sns.load_dataset("mpg")

In [4]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [5]:
df.shape

(398, 9)

In [6]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [8]:
df.select_dtypes(include=["object"])

origin                       name
0       usa  chevrolet chevelle malibu
1       usa          buick skylark 320
2       usa         plymouth satellite
3       usa              amc rebel sst
4       usa                ford torino
..      ...                        ...
393     usa            ford mustang gl
394  europe                  vw pickup
395     usa              dodge rampage
396     usa                ford ranger
397     usa                 chevy s-10

[398 rows x 2 columns]

In [9]:
df.nunique(axis=0)

mpg             129
cylinders         5
displacement     82
horsepower       93
weight          351
acceleration     95
model_year       13
origin            3
name            305
dtype: int64

In [10]:
df.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.469388  2970.424623   
std      7.815984    1.701004    104.269838   38.491160   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   75.000000  2223.750000   
50%     23.000000    4.000000    148.500000   93.500000  2803.500000   
75%     29.000000    8.000000    262.000000  126.000000  3608.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model_year  
count    398.000000  398.000000  
mean      15.568090   76.010050  
std        2.757689    3.697627  
min        8.000000   70.000000  
25%       13.825000   73.000000  
50%       15.500000   76.000000  
75%       17.175000   79.000000  
max       24.800000   82.000000

### Population and Sample

In [12]:
import numpy as np

In [13]:
np.random.seed(101)
population = np.random.randint(0,100, size = 100000)

In [14]:
population

array([95, 11, 81, ..., 72, 75, 64])

In [15]:
len(population)

100000

In [16]:
np.random.seed(101)
sample = np.random.choice(population, 100 )

In [17]:
sample

array([48, 99, 63, 36, 99, 38, 76, 63, 91, 53, 75, 62, 23, 13,  8, 83, 10,
       15, 80,  8, 56,  6, 85, 87, 22, 97, 51, 26, 75, 47, 86, 21, 10, 90,
       31, 66, 30, 66, 63,  8, 89, 24, 79, 45,  9,  1, 54, 91, 58,  4, 89,
        1, 38, 55, 21, 28, 43, 26, 23, 85, 98, 52, 19, 99, 56, 16, 87, 10,
       64, 44, 44, 71, 84, 83, 76, 47, 41, 54, 71,  7,  1, 17, 61, 35, 57,
       95, 87, 67, 52, 91, 68, 14, 88, 77, 96, 39,  5, 27, 40, 49])

In [18]:
population.mean()

49.41751

In [19]:
sample.mean()

51.18

In [20]:
sample_means = []
for i in range(100):
  sample = np.random.choice(population, 100)
  sample_means.append(sample.mean())

sample_means

[46.76,
 52.19,
 47.11,
 49.99,
 47.96,
 48.65,
 45.11,
 44.77,
 48.23,
 48.71,
 54.62,
 47.39,
 51.04,
 48.54,
 49.24,
 50.05,
 51.52,
 41.73,
 48.25,
 49.62,
 50.62,
 59.95,
 49.06,
 47.69,
 47.87,
 47.91,
 49.26,
 54.46,
 46.34,
 43.51,
 49.07,
 51.43,
 46.62,
 48.43,
 51.95,
 55.1,
 48.96,
 46.84,
 43.39,
 53.85,
 46.64,
 47.78,
 49.71,
 46.96,
 46.97,
 49.07,
 49.82,
 50.19,
 47.97,
 56.52,
 48.47,
 48.05,
 48.32,
 51.01,
 51.86,
 45.76,
 46.24,
 46.24,
 49.35,
 51.22,
 49.42,
 47.2,
 50.15,
 50.1,
 51.37,
 53.2,
 50.1,
 47.67,
 49.87,
 53.32,
 46.05,
 51.11,
 46.69,
 54.87,
 55.35,
 54.88,
 55.59,
 47.79,
 48.6,
 48.49,
 46.37,
 50.92,
 51.97,
 51.28,
 53.46,
 46.66,
 49.61,
 50.98,
 55.41,
 51.27,
 46.57,
 56.64,
 43.12,
 48.12,
 48.04,
 47.38,
 53.22,
 45.86,
 52.19,
 44.49]

In [21]:
np.mean(sample_means) 

49.4732

### Mean Median Mode Skewness 

In [23]:
import numpy as np
from scipy import stats

In [24]:
age = [20, 22, 25, 25, 27, 27, 27, 29, 30, 31, 121]

In [25]:
np.mean(age)

34.90909090909091

In [26]:
np.median(age)

27.0

In [27]:
stats.mode(age)

ModeResult(mode=array([27]), count=array([3]))

In [28]:
stats.mode(age)[0]

array([27])

In [29]:
import pandas as pd

In [30]:
data = {"D1":[135, 137, 136, 138, 138],

              "D2":[43,   42, 42, 42, 42],

              "D3":[72, 73, 72, 72, 73],

              "D4":[100, 102, 100, 103, 104]};

In [31]:
df = pd.DataFrame(data)

In [32]:
df

D1  D2  D3   D4
0  135  43  72  100
1  137  42  73  102
2  136  42  72  100
3  138  42  72  103
4  138  42  73  104

In [34]:
df.mean()

D1    136.8
D2     42.2
D3     72.4
D4    101.8
dtype: float64

In [35]:
df["D2"].mean()

42.2

In [36]:
df["D1"].mode()

0    138
dtype: int64

In [38]:
df["D4"].median()

102.0

### Dispersion

In [39]:
age = [20, 22, 25, 25, 27, 27, 27, 29, 30, 31]


In [40]:
np.std(age)

3.2572994949804666

In [41]:
age2 = [20, 22, 25, 25, 27, 27, 27, 29, 30, 31, 121]

In [42]:
np.std(age2)

27.400910885504736

In [43]:
np.max(age2) - np.min(age2)

101

In [44]:
np.var(age2)

750.809917355372

In [45]:
from scipy.stats import iqr

In [46]:
iqr(age2)

4.5

In [48]:
q1 = np.percentile(age2, 25)
q3 = np.percentile(age2, 75)

In [49]:
iqr = q3 - q1
iqr

4.5

In [51]:
q2 = np.percentile(age2, 50)
q2

27.0

In [52]:
np.median(age2)

27.0

In [53]:
##skewness
stats.skew(age2)

2.778572264050739

In [54]:
#kurtosiss  .  basıklık degeri
stats.kurtosis(age2)

5.876609699981859